In [1]:
import pandas as pd
import numpy as np

In [2]:
# LOAD DATASET

df = pd.read_csv("../data/Retail_Transaction_Dataset.csv")

df.head()

,CustomerID,ProductID,Quantity,Price,TransactionDate,PaymentMethod,StoreLocation,ProductCategory,DiscountApplied(%),TotalAmount
0,109318,C,7,80.079844,12/26/2025 12:32,Cash,"176 Andrew Cliffs\nBaileyfort, HI 93354",Books,18.677100,455.862764
1,993229,C,4,75.195229,08-05-2025 00:00,Cash,"11635 William Well Suite 809\nEast Kara, MT 19483",Home Decor,14.121365,258.306546
2,579675,A,8,31.528816,03-11-2026 18:51,Cash,"910 Mendez Ville Suite 909\nPort Lauraland, MO...",Books,15.943701,212.015651
3,799826,D,5,98.880218,10/27/2025 22:00,PayPal,"87522 Sharon Corners Suite 500\nLake Tammy, MO...",Books,6.686337,461.343769
4,121413,A,7,93.188512,12/22/2025 11:38,Cash,"0070 Michelle Island Suite 143\nHoland, VA 80142",Electronics,4.030096,626.030484

In [3]:
# DATASET SHAPE

print("Shape of Dataset:", df.shape)

Shape of Dataset: (100000, 10)

In [4]:
# DATASET INFORMATION

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   CustomerID          100000 non-null  int64
 1   ProductID           100000 non-null  str
 2   Quantity            100000 non-null  int64
 3   Price               100000 non-null  float64
 4   TransactionDate     100000 non-null  str
 5   PaymentMethod       100000 non-null  str
 6   StoreLocation       100000 non-null  str
 7   ProductCategory     100000 non-null  str
 8   DiscountApplied(%)  100000 non-null  float64
 9   TotalAmount         100000 non-null  float64
dtypes: float64(3), int64(2), str(5)
memory usage: 7.6 MB

In [5]:
# MISSING VALUES

print(df.isnull().sum())

CustomerID            0
ProductID             0
Quantity              0
Price                 0
TransactionDate       0
PaymentMethod         0
StoreLocation         0
ProductCategory       0
DiscountApplied(%)    0
TotalAmount           0
dtype: int64

In [6]:
# DUPLICATE RECORDS

print("Duplicate Rows =", df.duplicated().sum())

Duplicate Rows = 0

In [7]:
# REMOVE DUPLICATE RECORDS

df.drop_duplicates(inplace=True)

print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (100000, 10)

In [8]:
# CONVERT DATE COLUMN


df["TransactionDate"] = pd.to_datetime(df["TransactionDate"], format="mixed")

print("Date Converted Successfully!")

Date Converted Successfully!

In [9]:
# CREATE DATE FEATURES

df["Year"] = df["TransactionDate"].dt.year
df["Month"] = df["TransactionDate"].dt.month
df["Day"] = df["TransactionDate"].dt.day
df["Week"] = df["TransactionDate"].dt.isocalendar().week.astype(int)
df["Quarter"] = df["TransactionDate"].dt.quarter
df["DayOfWeek"] = df["TransactionDate"].dt.day_name()
df["Weekend"] = df["TransactionDate"].dt.dayofweek >= 5

df.head()

,CustomerID,ProductID,Quantity,Price,TransactionDate,PaymentMethod,StoreLocation,ProductCategory,DiscountApplied(%),TotalAmount,Year,Month,Day,Week,Quarter,DayOfWeek,Weekend
0,109318,C,7,80.079844,2025-12-26 12:32:00,Cash,"176 Andrew Cliffs\nBaileyfort, HI 93354",Books,18.677100,455.862764,2025,12,26,52,4,Friday,False
1,993229,C,4,75.195229,2025-08-05 00:00:00,Cash,"11635 William Well Suite 809\nEast Kara, MT 19483",Home Decor,14.121365,258.306546,2025,8,5,32,3,Tuesday,False
2,579675,A,8,31.528816,2026-03-11 18:51:00,Cash,"910 Mendez Ville Suite 909\nPort Lauraland, MO...",Books,15.943701,212.015651,2026,3,11,11,1,Wednesday,False
3,799826,D,5,98.880218,2025-10-27 22:00:00,PayPal,"87522 Sharon Corners Suite 500\nLake Tammy, MO...",Books,6.686337,461.343769,2025,10,27,44,4,Monday,False
4,121413,A,7,93.188512,2025-12-22 11:38:00,Cash,"0070 Michelle Island Suite 143\nHoland, VA 80142",Electronics,4.030096,626.030484,2025,12,22,52,4,Monday,False

In [10]:
# CREATE SEASON FEATURE

def get_season(month):

    if month in [12,1,2]:
        return "Winter"

    elif month in [3,4,5]:
        return "Summer"

    elif month in [6,7,8]:
        return "Monsoon"

    else:
        return "Autumn"

df["Season"] = df["Month"].apply(get_season)

df.head()

,CustomerID,ProductID,Quantity,Price,TransactionDate,PaymentMethod,StoreLocation,ProductCategory,DiscountApplied(%),TotalAmount,Year,Month,Day,Week,Quarter,DayOfWeek,Weekend,Season
0,109318,C,7,80.079844,2025-12-26 12:32:00,Cash,"176 Andrew Cliffs\nBaileyfort, HI 93354",Books,18.677100,455.862764,2025,12,26,52,4,Friday,False,Winter
1,993229,C,4,75.195229,2025-08-05 00:00:00,Cash,"11635 William Well Suite 809\nEast Kara, MT 19483",Home Decor,14.121365,258.306546,2025,8,5,32,3,Tuesday,False,Monsoon
2,579675,A,8,31.528816,2026-03-11 18:51:00,Cash,"910 Mendez Ville Suite 909\nPort Lauraland, MO...",Books,15.943701,212.015651,2026,3,11,11,1,Wednesday,False,Summer
3,799826,D,5,98.880218,2025-10-27 22:00:00,PayPal,"87522 Sharon Corners Suite 500\nLake Tammy, MO...",Books,6.686337,461.343769,2025,10,27,44,4,Monday,False,Autumn
4,121413,A,7,93.188512,2025-12-22 11:38:00,Cash,"0070 Michelle Island Suite 143\nHoland, VA 80142",Electronics,4.030096,626.030484,2025,12,22,52,4,Monday,False,Winter

In [11]:
# DATASET INFORMATION AFTER PREPROCESSING

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   CustomerID          100000 non-null  int64
 1   ProductID           100000 non-null  str
 2   Quantity            100000 non-null  int64
 3   Price               100000 non-null  float64
 4   TransactionDate     100000 non-null  datetime64[us]
 5   PaymentMethod       100000 non-null  str
 6   StoreLocation       100000 non-null  str
 7   ProductCategory     100000 non-null  str
 8   DiscountApplied(%)  100000 non-null  float64
 9   TotalAmount         100000 non-null  float64
 10  Year                100000 non-null  int32
 11  Month               100000 non-null  int32
 12  Day                 100000 non-null  int32
 13  Week                100000 non-null  int64
 14  Quarter             100000 non-null  int32
 15  DayOfWeek           100000 non-null  str
 16  Weekend             100000 non-null  bool
 17  Season              100000 non-null  str
dtypes: bool(1), datetime64[us](1), float64(3), int32(4), int64(3), str(6)
memory usage: 11.5 MB

In [12]:
# PREPROCESSED DATASET

df.head()

,CustomerID,ProductID,Quantity,Price,TransactionDate,PaymentMethod,StoreLocation,ProductCategory,DiscountApplied(%),TotalAmount,Year,Month,Day,Week,Quarter,DayOfWeek,Weekend,Season
0,109318,C,7,80.079844,2025-12-26 12:32:00,Cash,"176 Andrew Cliffs\nBaileyfort, HI 93354",Books,18.677100,455.862764,2025,12,26,52,4,Friday,False,Winter
1,993229,C,4,75.195229,2025-08-05 00:00:00,Cash,"11635 William Well Suite 809\nEast Kara, MT 19483",Home Decor,14.121365,258.306546,2025,8,5,32,3,Tuesday,False,Monsoon
2,579675,A,8,31.528816,2026-03-11 18:51:00,Cash,"910 Mendez Ville Suite 909\nPort Lauraland, MO...",Books,15.943701,212.015651,2026,3,11,11,1,Wednesday,False,Summer
3,799826,D,5,98.880218,2025-10-27 22:00:00,PayPal,"87522 Sharon Corners Suite 500\nLake Tammy, MO...",Books,6.686337,461.343769,2025,10,27,44,4,Monday,False,Autumn
4,121413,A,7,93.188512,2025-12-22 11:38:00,Cash,"0070 Michelle Island Suite 143\nHoland, VA 80142",Electronics,4.030096,626.030484,2025,12,22,52,4,Monday,False,Winter

In [13]:
# SAVE PREPROCESSED DATASET

df.to_csv("../data/preprocessed_data.csv", index=False)

print("Preprocessed Dataset Saved Successfully!")

Preprocessed Dataset Saved Successfully!

In [14]:
## Preprocessing Summary

#- Removed duplicate records.
#- Converted TransactionDate to datetime format.
#- Extracted Year, Month, Day, Week, Quarter and DayOfWeek.
#- Identified Weekend transactions.
#- Created Season feature.
#- Saved the cleaned dataset for forecasting.