In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/Retail_Transaction_Dataset.csv")

df.head()

,CustomerID,ProductID,Quantity,Price,TransactionDate,PaymentMethod,StoreLocation,ProductCategory,DiscountApplied(%),TotalAmount
0,109318,C,7,80.079844,12/26/2023 12:32,Cash,"176 Andrew Cliffs\nBaileyfort, HI 93354",Books,18.677100,455.862764
1,993229,C,4,75.195229,8/5/2023 0:00,Cash,"11635 William Well Suite 809\nEast Kara, MT 19483",Home Decor,14.121365,258.306546
2,579675,A,8,31.528816,3/11/2024 18:51,Cash,"910 Mendez Ville Suite 909\nPort Lauraland, MO...",Books,15.943701,212.015651
3,799826,D,5,98.880218,10/27/2023 22:00,PayPal,"87522 Sharon Corners Suite 500\nLake Tammy, MO...",Books,6.686337,461.343769
4,121413,A,7,93.188512,12/22/2023 11:38,Cash,"0070 Michelle Island Suite 143\nHoland, VA 80142",Electronics,4.030096,626.030484

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   CustomerID          100000 non-null  int64
 1   ProductID           100000 non-null  str
 2   Quantity            100000 non-null  int64
 3   Price               100000 non-null  float64
 4   TransactionDate     100000 non-null  str
 5   PaymentMethod       100000 non-null  str
 6   StoreLocation       100000 non-null  str
 7   ProductCategory     100000 non-null  str
 8   DiscountApplied(%)  100000 non-null  float64
 9   TotalAmount         100000 non-null  float64
dtypes: float64(3), int64(2), str(5)
memory usage: 7.6 MB

In [4]:
df.isnull().sum()

CustomerID            0
ProductID             0
Quantity              0
Price                 0
TransactionDate       0
PaymentMethod         0
StoreLocation         0
ProductCategory       0
DiscountApplied(%)    0
TotalAmount           0
dtype: int64

In [5]:
mean_amount = df["TotalAmount"].mean()
std_amount = df["TotalAmount"].std()

upper_limit = mean_amount + 3 * std_amount
lower_limit = mean_amount - 3 * std_amount

print("Mean:", mean_amount)
print("Standard Deviation:", std_amount)
print("Upper Limit:", upper_limit)
print("Lower Limit:", lower_limit)

Mean: 248.3349550638552
Standard Deviation: 184.55479200874532
Upper Limit: 801.9993310900911
Lower Limit: -305.3294209623807

In [6]:
anomalies = df[
    (df["TotalAmount"] > upper_limit) |
    (df["TotalAmount"] < lower_limit)
]

anomalies.head()

,CustomerID,ProductID,Quantity,Price,TransactionDate,PaymentMethod,StoreLocation,ProductCategory,DiscountApplied(%),TotalAmount
464,493138,D,9,99.999284,9/27/2023 23:40,Credit Card,"766 Bryant Lock\nNorth Ashley, MP 73093",Clothing,2.093143,881.155400
1059,741281,A,9,90.363791,5/10/2023 13:01,Debit Card,"9614 Randall Walks Apt. 834\nWest Lindseyton, ...",Electronics,1.267586,802.965172
1077,456529,A,9,98.316860,7/24/2023 12:54,Credit Card,"36883 Brian Port\nAnthonyton, NV 72907",Electronics,5.563012,835.627328
1087,70193,A,9,99.888441,3/28/2024 19:34,Cash,"93871 Nicholson Heights\nUnderwoodstad, SD 59640",Electronics,1.850444,882.360550
1229,387464,A,9,98.712411,10/15/2023 1:13,PayPal,"00896 Eric Center\nLake Luis, PW 41525",Electronics,8.699155,811.127387

In [7]:
print("Total Transactions:", len(df))
print("Anomalies Found:", len(anomalies))

Total Transactions: 100000
Anomalies Found: 395

In [8]:
anomalies.sort_values(
    "TotalAmount",
    ascending=False
).head(10)

,CustomerID,ProductID,Quantity,Price,TransactionDate,PaymentMethod,StoreLocation,ProductCategory,DiscountApplied(%),TotalAmount
52097,649087,C,9,99.815185,7/27/2023 13:40,Debit Card,"693 Williams Pine\nRobertside, WI 23415",Home Decor,0.244387,896.141242
97808,266635,D,9,99.618873,4/11/2024 22:47,Credit Card,"8978 Angela Forge\nGrossfort, LA 99907",Books,0.136732,895.343955
97083,590301,A,9,99.908285,10/9/2023 10:09,Debit Card,"0303 Keith Manor\nJuliaport, NY 08811",Books,0.630034,893.509454
30448,590260,A,9,99.552733,11/9/2023 1:51,Debit Card,"797 Sanders Landing Apt. 719\nNorth Terry, NY ...",Books,0.383498,892.538546
41342,55183,B,9,99.644161,7/17/2023 1:04,Cash,"8889 Carr Mission\nRonaldview, TN 69021",Home Decor,0.506715,892.253248
79012,388796,B,9,99.507283,2/10/2024 0:40,Cash,USNV Diaz\nFPO AA 22844,Home Decor,0.371317,892.240154
63287,957063,A,9,99.543715,1/18/2024 21:50,Cash,"9432 King Keys\nSchmidttown, MA 64018",Electronics,0.566104,890.821751
95654,711672,D,9,99.895499,3/2/2024 13:22,Debit Card,"3180 Danielle Canyon\nMorrisonland, MA 50656",Books,0.931076,890.688556
76294,199840,C,9,99.538757,4/17/2024 9:14,Credit Card,"35822 Andrews Trace\nLandrymouth, VI 18721",Clothing,0.747900,889.148765
85923,103767,B,9,99.168399,11/16/2023 12:58,Debit Card,USNS Blake\nFPO AE 15466,Clothing,0.459150,888.417599

In [9]:
df["Anomaly"] = np.where(
    (df["TotalAmount"] > upper_limit) |
    (df["TotalAmount"] < lower_limit),
    "Anomaly",
    "Normal"
)

df.head()

,CustomerID,ProductID,Quantity,Price,TransactionDate,PaymentMethod,StoreLocation,ProductCategory,DiscountApplied(%),TotalAmount,Anomaly
0,109318,C,7,80.079844,12/26/2023 12:32,Cash,"176 Andrew Cliffs\nBaileyfort, HI 93354",Books,18.677100,455.862764,Normal
1,993229,C,4,75.195229,8/5/2023 0:00,Cash,"11635 William Well Suite 809\nEast Kara, MT 19483",Home Decor,14.121365,258.306546,Normal
2,579675,A,8,31.528816,3/11/2024 18:51,Cash,"910 Mendez Ville Suite 909\nPort Lauraland, MO...",Books,15.943701,212.015651,Normal
3,799826,D,5,98.880218,10/27/2023 22:00,PayPal,"87522 Sharon Corners Suite 500\nLake Tammy, MO...",Books,6.686337,461.343769,Normal
4,121413,A,7,93.188512,12/22/2023 11:38,Cash,"0070 Michelle Island Suite 143\nHoland, VA 80142",Electronics,4.030096,626.030484,Normal

In [12]:
df.to_csv(
    "../data/anomaly_detection.csv",
    index=False
)

print("Anomaly Detection Data Saved Successfully!")

Anomaly Detection Data Saved Successfully!